site_name: 'Yandex YML — Drupal module'
theme:
  name: 'material'
pages:
  - 'Home': index.md
  - 'Installation': installation.md
  - 'API overview': api-overview.md
  - 'Generator service': generator-service.md
  - 'Element objects': element-objects.md
