site_name: 'Yandex YML — Drupal module'
pages:
  - 'Home': index.md
  - 'Installation': installation.md
  - 'How it works': how-it-works.md
  - 'Generate YML': generate-yml.md
  - 'Real world examples': real-examples.md